#! /bin/sh

# bspwm border and window gap
bspc config border_width       2
bspc config window_gap         10

# add some padding on top for the panel
# bspc config top_padding 15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
# bspc config focus_by_distance   true

bspc config normal_border_color "#282c34"
# bspc config active_border_color "#62AFEE"
# bspc config focused_border_color "#62AFEE"
bspc config presel_border_color "#C678DD"
# bspc config urgent_border_color "#E06C75"
# bspc config focused_locked_border_color "#E06C75"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor -d I II III IV V

bspc rule -a nautilus border=off manage=off
bspc rule -a File-roller pseudo_tiled=on border=off
bspc rule -a Transmission-gtk pseudo_tiled=on border=off

bspc rule -a google-chrome-stable desktop=^1 fullscreen=true border=off
bspc rule -a atom desktop=^2 fullscreen=true border=off

# panel &
