#! /bin/sh

# bspwm border and window gap
bspc config border_width       2
bspc config window_gap         15

# add some padding on top for the panel
bspc config top_padding 15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
# bspc config focus_by_distance   true

bspc config normal_border_color "#282828"
bspc config active_border_color "#7cafc2"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#BA8BAF"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor -d I II III IV V

panel &
